  deploy:
    machine:
      enabled: true
    working_directory: ~/circle-tmp-folder
    steps:
       - run:
          name: Deploy
          command: 'aws s3 sync ${source}/ s3://iwc-ci-demo --region eu-west-1'