version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

    # install python and awscli
      - run:
          name: Install dependencies
          working_directory: /
          command: sudo apt-get -y -qq install awscli

      - run:
          name: Deploy application
          command: aws s3 cp junaid.html s3://circle123